#############################################################################
# Makefile for building: Robomaster2018
# Generated by qmake (2.01a) (Qt 4.8.7) on: ?? 2? 1 14:51:47 2020
# Project:  Robomaster2018.pro
# Template: app
# Command: /usr/lib/x86_64-linux-gnu/qt4/bin/qmake -spec /usr/share/qt4/mkspecs/linux-g++-64 CONFIG+=debug -o Makefile Robomaster2018.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = 
CFLAGS        = -m64 -pipe -g -Wall -W $(DEFINES)
CXXFLAGS      = -m64 -pipe -g -Wall -W $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/home/zhaolin/QT/Robomaster2018-SEU-OpenSource-master/../../../usr/local/cuda/include -IDarknet -I/usr/local/include/opencv -I/usr/local/include
LINK          = g++
LFLAGS        = -m64
LIBS          = $(SUBLIBS)   -L/home/zhaolin/QT/Robomaster2018-SEU-OpenSource-master/../../../usr/local/cuda/lib64/-lcudart -L/home/zhaolin/QT/Robomaster2018-SEU-OpenSource-master/../../../usr/local/cuda/lib64/-lcuda -L/home/zhaolin/QT/Robomaster2018-SEU-OpenSource-master/../../../usr/local/cuda/lib64/-lcublas -L/home/zhaolin/QT/Robomaster2018-SEU-OpenSource-master/../../../usr/local/cuda/lib64/-lcurand -lpthread -lv4l2 -L/home/zhaolin/QT/Robomaster2018-SEU-OpenSource-master/Darknet/ -ldarknet -L/usr/local/lib -lopencv_dnn -lopencv_highgui -lopencv_ml -lopencv_objdetect -lopencv_shape -lopencv_stitching -lopencv_superres -lopencv_videostab -lopencv_calib3d -lopencv_videoio -lopencv_imgcodecs -lopencv_features2d -lopencv_video -lopencv_photo -lopencv_imgproc -lopencv_flann -lopencv_core 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/lib/x86_64-linux-gnu/qt4/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = General/opencv_extended.cpp \
		General/numeric_rm.cpp \
		Driver/RMVideoCapture.cpp \
		Serials/Serial.cpp \
		Main/ImgProdCons.cpp \
		Pose/Predictor.cpp \
		Pose/AngleSolver.cpp \
		Armor/ArmorDetector.cpp \
		Rune/Rune.cpp \
		Main/main.cpp \
		Main/test_sentry.cpp 
OBJECTS       = opencv_extended.o \
		numeric_rm.o \
		RMVideoCapture.o \
		Serial.o \
		ImgProdCons.o \
		Predictor.o \
		AngleSolver.o \
		ArmorDetector.o \
		Rune.o \
		main.o \
		test_sentry.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/link_pkgconfig.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		Robomaster2018.pro
QMAKE_TARGET  = Robomaster2018
DESTDIR       = 
TARGET        = Robomaster2018

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)
	{ test -n "$(DESTDIR)" && DESTDIR="$(DESTDIR)" || DESTDIR=.; } && test $$(gdb --version | sed -e 's,[^0-9][^0-9]*\([0-9]\)\.\([0-9]\).*,\1\2,;q') -gt 72 && gdb --nx --batch --quiet -ex 'set confirm off' -ex "save gdb-index $$DESTDIR" -ex quit '$(TARGET)' && test -f $(TARGET).gdb-index && objcopy --add-section '.gdb_index=$(TARGET).gdb-index' --set-section-flags '.gdb_index=readonly' '$(TARGET)' '$(TARGET)' && rm -f $(TARGET).gdb-index || true

Makefile: Robomaster2018.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/link_pkgconfig.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++-64 CONFIG+=debug -o Makefile Robomaster2018.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/debug.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/link_pkgconfig.prf:
/usr/share/qt4/mkspecs/features/shared.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++-64 CONFIG+=debug -o Makefile Robomaster2018.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/Robomaster20181.0.0 || $(MKDIR) .tmp/Robomaster20181.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/Robomaster20181.0.0/ && (cd `dirname .tmp/Robomaster20181.0.0` && $(TAR) Robomaster20181.0.0.tar Robomaster20181.0.0 && $(COMPRESS) Robomaster20181.0.0.tar) && $(MOVE) `dirname .tmp/Robomaster20181.0.0`/Robomaster20181.0.0.tar.gz . && $(DEL_FILE) -r .tmp/Robomaster20181.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

opencv_extended.o: General/opencv_extended.cpp General/opencv_extended.h \
		General/numeric_rm.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o opencv_extended.o General/opencv_extended.cpp

numeric_rm.o: General/numeric_rm.cpp General/numeric_rm.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o numeric_rm.o General/numeric_rm.cpp

RMVideoCapture.o: Driver/RMVideoCapture.cpp Driver/RMVideoCapture.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o RMVideoCapture.o Driver/RMVideoCapture.cpp

Serial.o: Serials/Serial.cpp Serials/Serial.h \
		General/General.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Serial.o Serials/Serial.cpp

ImgProdCons.o: Main/ImgProdCons.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ImgProdCons.o Main/ImgProdCons.cpp

Predictor.o: Pose/Predictor.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Predictor.o Pose/Predictor.cpp

AngleSolver.o: Pose/AngleSolver.cpp Pose/AngleSolver.hpp \
		General/General.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o AngleSolver.o Pose/AngleSolver.cpp

ArmorDetector.o: Armor/ArmorDetector.cpp Armor/ArmorDetector.h \
		General/General.h \
		General/opencv_extended.h \
		General/numeric_rm.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ArmorDetector.o Armor/ArmorDetector.cpp

Rune.o: Rune/Rune.cpp Rune/Rune.h \
		General/singleton.hpp \
		General/General.h \
		General/opencv_extended.h \
		General/numeric_rm.h \
		Darknet/src/yolo_v2_class.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Rune.o Rune/Rune.cpp

main.o: Main/main.cpp Main/ImgProdCons.h \
		Driver/RMVideoCapture.hpp \
		Serials/Serial.h \
		Pose/AngleSolver.hpp \
		General/General.h \
		Armor/ArmorDetector.h \
		Rune/Rune.h \
		General/singleton.hpp \
		General/opencv_extended.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o Main/main.cpp

test_sentry.o: Main/test_sentry.cpp Main/ImgProdCons.h \
		Driver/RMVideoCapture.hpp \
		Serials/Serial.h \
		Pose/AngleSolver.hpp \
		General/General.h \
		Armor/ArmorDetector.h \
		Rune/Rune.h \
		General/singleton.hpp \
		General/opencv_extended.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o test_sentry.o Main/test_sentry.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

